### ISSUE TITLE
Tabs are now broken

### ISSUE THREAD

**Issue by kory-u** [Seraaron/roll20-character-sheets#3] opened 2020-11-30 22:02 UTC
Changing tabs suddenly stopped working in the middle of a session

**Comment by rotoclone** [comment] 2020-12-01 01:52
My group is also seeing this, I created an issue on the main repo for it before I found the link to this fork in the readme: https://github.com/Roll20/roll20-character-sheets/issues/7819

**Comment by jaredskarma** [comment] 2020-12-01 01:58
The updated sheet looks great and I'm loving the new Rogues tab, but my group is also currently experiencing the broken tabs issue.

**Comment by Anduh** [comment] 2020-12-01 19:51
Roll20 Character Sheet Backend Changes where rolled out yesterday, are likely the cause of this issue. Seem [my comment](https://app.roll20.net/forum/permalink/9556767/) in the main thread for an full explanation.

The issue is identified, and a fix will be out later today, is what I was just told.

**Comment by rotoclone** [comment] 2020-12-03 03:29
It's working for me as of today

**Comment by Seraaron** [comment] 2020-12-07 18:32
Yeah this was a server-wide issue with many sheets, not the the Burning Wheel one. Not my fault, luckily! But I think it's already been fixed by the R20 team

**Closed as completed by Seraaron** 2020-12-07 18:32 UTC
