### ISSUE TITLE
13th Age Glorantha Sheet - Critical damage roll button macro request

### ISSUE THREAD

**Issue by SirKeith68** [Seraaron/roll20-character-sheets#15] opened 2022-04-07 20:39 UTC
Hi there - just kicking off a new 13th Age Campaign. Thanks for all the work on the sheet.
I had a question...
The sheet tracks 'Uses' of a power, both current and max. i.e. I can use this power 6 times in a day, and I've currently used in twice. 
When I roll the power I calculate and display the Hit Roll and Damage. Is there a way to also increment the current count field on the character sheet when I 'roll' the power?

Inquiring over on the Roll20 Discord, the suggestion was:
'If the game was created by a pro subscriber, they could install the ammo or chatsetattr scripts to be able to do something like that.  Otherwise, macros can read sheet attributes, but can't alter them.  That is something that generally requires the api.'

**Comment by Seraaron** [comment] 2022-11-11 14:09
No there is no way to do this that I know of, sorry. Not without more open javascript access (which is deliberately very limited or security reasons) or full API access (which is a feature that only pro level subscribers get and I have no idea how to use).

**Comment by norev** [comment] 2022-11-20 20:18
Hello @Seraaron 

As this issue's title was very generic, I'll add a comment/question here.

Does the sheet calculate critical damage correctly? To me it seems it isn't, or I am not understanding something correctly.

Character is level 1, his weapon does d6 damage and his STR bonus is 2. He rolls a crit (20), the damage shows 5, calculated like this:

(1*1)d6+2 = (3)+2

Shouldn't the damage be double, i.e. 10?

Thanks!

![Screenshot 2022-11-20 at 22 17 12](https://user-images.githubusercontent.com/6938055/202924092-22b172ab-2629-411b-9454-1fbafa57cb32.png)

**Comment by Seraaron** [comment] 2022-11-21 20:14
Good question! I haven't looked at this sheet or played 13th Age in over a year, but I'm currently making a new sheet for another game, so I may be able to add a fix in the not too distant future.

But with a cursory glance (and remembering how I designed this sheet), I think it doesn't automatically calculate crits on purpose. You can go to the settings tab and see how the macros are calculated. Pressing the 'melee' attack button basically just calls @{pma} and @{pmd} in sequence. IRRC there's no easy way to reference a previous roll even from within the same macro. Like, there's no conditional logic in macros I don't think... So I can't write something that says `if @{core}==20 then @{pmd}*2`

If you know of any other sheet that does this then let me know and I'll have a look at it to see if this is a solved problem and I'm just trying to reinvent the wheel.

**Comment by Seraaron** [comment] 2022-11-21 20:18
Or if there is a way to do it then it's possible that I left it uncalculated on purpose because I seem to remember there being multiple different optional rules in 13A about what to do with crits. So it may be that I figured each group would decide for themselves if crits double or whatever. You can still quite clearly see when a crit should happen from the blue highlighting, at least, and it's not that hard to double a number in your head.

**Comment by norev** [comment] 2022-11-22 04:53
@Seraaron Thanks for the quick answer. I haven't read all the 13th Age Core classes in much detail, but from 13th Age Glorantha I cannot remember there being other effects from crits than doubling the damage. I could be wrong though. What there is though, is that the crit range can differ from character to character, so some characters would crit also on a 19 for example. So in that sense it might be good to never double the damage, and just leave it to the players to figure it out if it is a crit or not.

But now that you mentioned other sheets, I checked how `D&D 5E by Roll20` sheet handles crits. It does it so that when you first roll the skill, there is a link for the weapon under the roll and when you click on that, it knows if the damage dice are rolled twice or not (5E damage is little different from 13th Age). Checking the links that the sheet creates under the skill rolls, when on that sheet you roll a crit, there is `damage_crit` at the end of the link, and `damage_dmg` with a normal roll, so I am guessing that's how you would need to do it if you would want to.

In the image below `4` is the normal damage is and `6` is from the die allowed by the crit.

<img width="204" alt="Screenshot 2022-11-22 at 6 45 02" src="https://user-images.githubusercontent.com/6938055/203223835-ba1b425b-d040-439b-8e64-94b506e197d0.png">

But anyway, yes, easy enough to double the damage in your head when needed, agreed!

**Comment by Seraaron** [comment] 2022-11-22 13:39
If I recall correctly the D&D sheet uses some pretty complex API scripts that I have no idea how to reproduce (or if it's even possible for a non-roll20 staff member to reproduce, since the D&D sheet has the official WotC seal of approval). I think the closest I can do is called 'peuso-referencing' which is what you already see, where the macro shows you how your roll is composed without needing to hover over the result with your mouse. But like I said, I'll have a closer look in the not-too-distant future and let you know :)

**Comment by norev** [comment] 2022-11-23 05:20
@Seraaron Yeah, tbh I don't think it would be worth the trouble anyway, probably would be a lot of work and so easy to double the number by yourself. Thanks for the great sheet, we're currently playing the Six Seasons in Sartar campaign with 13th Age rules.

**Comment by Seraaron** [comment] 2022-12-05 21:12
It looks like there might be a way to do this without API scripting after all! but my current project is more demanding than I thought it would (making a whole new sheet for another game from scratch) be. So it might be a little while yet before I come back around to adding this to the glorantha sheet.

Note for future reference this functionality is called a [Chat Menu](https://wiki.roll20.net/Chat_Menu)

**Comment by norev** [comment] 2022-12-07 06:44
@Seraaron No worries, good luck with the new project! What game is it for, if I may ask (just curious) ?

**Comment by Seraaron** [comment] 2022-12-07 17:21
@norev The game called 'ICON' by massif press. It's still in playtesting / development, but it's free on itch.io 
similar kind of game to Exalted, or Godbound, but with more JRPG inspiration in it's combat system

**Comment by norev** [comment] 2022-12-08 07:10
@Seraaron Nice, I downloaded it and I'll give it a look later.

**Comment by Seraaron** [comment] 2023-01-22 15:21
Okay so I finished the ICON sheet and looked at this properly, finally. It seems like my own smartassery is coming back to bite me now. Basically I designed the 13G sheet very early in my web-dev learning experience, and I made a lot of (in hindsight) very weird decisions to work around certain problems and to calculate things in a unique way, because I didn't know any better, while also trying to leave as much of it exposed to be edited and fiddled with in the settings menu. In effect, what this means is that while the sheet is very flexible for the end user, it makes it very difficult for me (or anyone else for that matter) to come back to and edit or add new stuff.

For me to add a chat menu to melee rolls for crits (or my other idea was to conditionally show crit damage if you roll above a certain amount) and still retain all the currently exposed code in the settings menu I think I'd need to rewrite roll macros from scratch... And that would potentially impose some 'breaking changes' that would affect all sheet users at this time. Ideally, the whole sheet would need to be updated from legacy mode and then it could take advantage of some new roll20 features, like custom roll parsers. But that would be a herculean task. It would probably be easier to make a whole new sheet honestly.

My pro subscription that gives me access to the shet development envrionment expires on Wednesday, and I have other projects to work on in Feb. So I think I'm gunna close the issue say that people can just double the numbers in their heads.

**Comment by norev** [comment] 2023-01-23 05:42
@Seraaron I understand totally, being a developer myself and still at times having to work with some legacy stuff that I coded decades ago :) Also, our gaming group in the end decided to change the system to HeroQuest Glorantha so for us this wasn't an issue anymore anyway (our decision to change the system had nothing to do with Roll20 or the character sheets). Your 13G character sheet is great and would recommend it to others. Thanks and all the best going forward!

**Comment by Seraaron** [comment] 2023-01-23 13:43
Cheers!

**Closed as completed by Seraaron** 2023-01-23 13:43 UTC
